### ISSUE TITLE
oneapi setvars.sh

### ISSUE THREAD

**Issue by cbyrohl** [samridh-dev/votess#1]
Hi Sam,

copying Dylan's issues over from the private repo:

> The documentation currently says this:
> 
> If compiled with the dpc++ compiler, the following command must be run in the terminal instance:
> 
> source /opt/intel/oneapi/setvars.sh
> 
> but this may vary system by system. On my computer, I have no file. Suggest to remove, perhaps just provide a link to some oneapi documentation instead which explains what this is doing/why it is necessary.
> 
> As a result,
> 
> $ bash make.sh
> make.sh: line 6: /opt/intel/oneapi/setvars.sh: No such file or directory

**Comment by samridh-dev** [comment]
I edited the README.md file to include installation steps on both intel oneAPI and AdaptiveCpp. I also added links to to setting environment variables via setvars.sh if using the intel compiler.

**Comment by cbyrohl** [comment]
Not all distributions, particularly on HPC resources, have the "setvars.sh" script located at `/opt/intel/oneapi/setvars.sh`.  Furthermore, the README implies one can use the AdaptiveCpp compiler instead of Intel oneAPI. Thus, I would recommend you move the setvars.sh out of the make.sh script. Instead provide a README subsection on environment preparation (for the Intel compiler in this case) or add optional environment scripts for the respective compilers and add some link to the respective oneapi documentation when the setvars.sh is not found at set location.

**Comment by samridh-dev** [comment]
Okay, I think the setvars.sh exists for the sake of my development. I will check for its existences and run it if necessary. Let me know if the code compiles then.

**Comment by dnelson86** [comment]
Can close this issue, now working (at least in my use case).

**Comment by samridh-dev** [comment]
Closing issue.
