### ISSUE TITLE
State of the CLI

### ISSUE THREAD

**Issue by cbyrohl** [samridh-dev/votess#4]
Can you update/clarify the state of the CLI in the README?

1. If the CLI is supported, set the CMake options to compile it by default, and provide the input file format in the README section.
2. If the CLI is no longer supported, make that clear in the README in the respective sections where it is mentioned

That said, running ./votess on a simple .dat positions file looks fine!

Minor things:

* No version output possible

```
byrohlc@vera02:~/repos/votess> ./bin/votess --help
Options:
 -h, --help              Show help
 -v, --version           Show version
 -i, --infile  <infile>  Specify input file. Required argument.
 -k, --k_init  <k_init>  Specify initial k for k-nearest neighbor search.

Error: Could not open file 
byrohlc@vera02:~/repos/votess> ./bin/votess --version
Error: Could not open file
```

**Comment by samridh-dev** [comment]
I updated the command line program to be a little more robust. Let me know if it looks better. I did not implement --version, since I currently do not have an official version for the program, as well as a standard syntax for such a program

**Comment by cbyrohl** [comment]
CLI looks fine:

> 
> byrohlc@vera02:~/repos/votess/bin> ./votess --help
> 
> Options:
>  -h, --help               Show help
>  -v, --version            Show version
>  -i, --infile   <infile>  Specify input file. Required argument.
>  -k, --k-init   <k_init>  Specify initial k for k-nearest neighbor search.
>  -g, --gridres  <k_init>  Specify grid resolution.

Any explanation of the respective parameters, particularly the file format for the input file in the CLI "votess --help" output itself and in the README would be helpful.

Another minor point: Readme mentions "votess --help-all" command, which no longer seems valid.

**Comment by dnelson86** [comment]
I just compiled, and there is no CLI (in the bin directory).

Is it compiled by default? (Needs to be).

**Comment by samridh-dev** [comment]
Set CLI program to compile by default.
