### ISSUE TITLE
Documentation on Target Selection

### ISSUE THREAD

**Issue by cbyrohl** [samridh-dev/votess#5]
Can you add some README description on how to select a target (primarily cpu vs gpu) either in votess directly (e.g. some parameter if implemented) or link and summarize how to set the compile or runtime target for Intel/adaptivecpp?

**Comment by samridh-dev** [comment]
In the c++ example in the README, there is a commented out line which runs the tesellation on a cpu target. Let me know if I should make this more explicit.

**Comment by samridh-dev** [comment]
Note: cpu implementation bugs have been fixed. All tests pass.
