### ISSUE TITLE
MPCDF compile

### ISSUE THREAD

**Issue by dnelson86** [samridh-dev/votess#6]
How to compile on MPCDF e.g. Vera?

Right now, I am at:

```bash
module purge
module load intel/2024.0
./make.sh

100%] Linking CXX shared module ../../../bin/pyvotess.so
[100%] Built target pyvotess
[100%] Linking CXX executable ../../../bin/test
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /tmp/icpx-34a978c956/votess-53c39f.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/CMakeFiles/test.dir/build.make:259: ../../bin/test] Error 1
make[1]: *** [CMakeFiles/Makefile2:1635: test/CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by samridh-dev** [comment]
To me this seems to be a linker error to the pthread library. Apparently it is a special case, where you have to link it separately. I added this line in cmake/dependencies: add_library(Threads::Threads INTERFACE IMPORTED)
Let me know if the compilation works.

**Comment by dnelson86** [comment]
Thanks, but the problem remains.

Possible related: https://stackoverflow.com/questions/19901934/libpthread-so-0-error-adding-symbols-dso-missing-from-command-line

**Comment by samridh-dev** [comment]
Okay. In that case, let me add the flag -pthread to compilation, and see if the gcc can find that symbol.
Let me know if there are still issues. Also, if there is a way where I can replicate the error on my machine, it would be helpful.

**Comment by dnelson86** [comment]
Thanks, compilation success.
